"""PostGrid-native letter HTML templates.

These are *not* Jinja2 templates — they use PostGrid's own {{merge}}
variable syntax and are uploaded to the PostGrid dashboard via the API so
Andy can edit formatting / spacing visually.

Merge variables expected (pass via mergeVariables in create_letter):
  salutation  – first name or "Sir or Madam"
  headline    – AI finding sentence
  town        – company's town, e.g. "Winchester"
  sector      – sector phrase, e.g. "solicitors"
  dateStr     – formatted date, e.g. "26 July 2026"
  claimUrl    – full claim URL incl https://

PostGrid auto-provides {{to.companyName}}, {{to.firstName}},
{{to.addressLine1}}, {{to.city}}, {{to.postalOrZip}}, etc.

QR code: generated by api.qrserver.com at PostGrid render time using
the claimUrl merge var substituted into the img src.

Layout mirrors the WeasyPrint-rendered PDF letters (the reference design):
  [Logo + name]                    [Sender address block, right-aligned]
  ─────────────────────────────────────────────────────────────────────
  [Recipient name]
  [Recipient company]
  [Recipient address]

  [Date]
  Dear [salutation],
  [Finding block — coral border + cream bg]
  [Body paragraphs]
  [Claim box — border + hard shadow — QR left + URL right]
  Best regards,
  Andy Norman
  Antek Automation
  PS. ...
  ─────────────────────────────────────────────────────────────────────
  [Footer: full sender address + website]
"""
from __future__ import annotations

import base64
import os

_HERE = os.path.dirname(__file__)
_LOGO_PATH = os.path.join(_HERE, "templates", "logo.svg")


def _logo_data_uri() -> str:
    try:
        with open(_LOGO_PATH, "rb") as fh:
            return "data:image/svg+xml;base64," + base64.b64encode(fh.read()).decode()
    except FileNotFoundError:
        return ""


# ── Shared CSS ──────────────────────────────────────────────────────────────

_SHARED_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;800&family=DM+Sans:wght@400;500;700&family=JetBrains+Mono:wght@400;700&display=swap');

/* Page margins for PostGrid print + browser screen preview */
@page { margin: 18mm 18mm; }
@media screen { body { padding: 18mm 18mm; max-width: 820px; margin: 0 auto; } }

* { margin: 0; padding: 0; box-sizing: border-box; border-radius: 0; }

body {
    font-family: 'DM Sans', 'Helvetica Neue', Arial, sans-serif;
    color: #2C2C2C;
    background: #FFFFFF;
    font-size: 11pt;
    line-height: 1.6;
}

/* ── Header: logo + name only — no sender address (PostGrid stamps that) ── */
.header {
    display: flex;
    align-items: center;
    padding-bottom: 10px;
    border-bottom: 2px solid #2C2C2C;
    margin-bottom: 16px;
}
.brandmark { display: flex; align-items: center; gap: 10px; }
.brandmark img { width: 44px; height: 44px; }
.brandmark .name {
    font-family: 'Outfit', 'Arial Black', sans-serif;
    font-weight: 800;
    font-size: 14pt;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    color: #2C2C2C;
}

/* ── Recipient address ── */
.addressee {
    font-size: 11pt;
    line-height: 1.5;
    margin-bottom: 32px;   /* increased — date removed, this gap replaces it */
    color: #2C2C2C;
    white-space: pre-line;  /* so \n in {{addrBlock}} renders as a line break */
}

/* ── Date (unused — kept for reference) ── */
.date {
    font-family: 'JetBrains Mono', 'Courier New', monospace;
    font-size: 9pt;
    color: #2C2C2C;
    margin-bottom: 16px;
}

/* ── Body ── */
.body { font-size: 11pt; line-height: 1.6; }
.body p { margin-bottom: 12px; }

/* ── Finding block: coral left border + cream background ── */
.finding {
    border-left: 5px solid #CD5C3C;
    padding: 9px 13px;
    background: #E8DCC8;
    font-weight: 600;
    font-size: 11pt;
    margin-bottom: 13px;
    line-height: 1.4;
}

/* ── Claim CTA: border + hard shadow, QR left + URL right ── */
.claim {
    margin: 14px 0 16px;
    border: 2px solid #2C2C2C;
    box-shadow: 4px 4px 0 #2C2C2C;
    padding: 12px 16px;
    background: #FFFFFF;
    display: flex;
    align-items: center;
    gap: 16px;
}
.claim img.qr {
    width: 110px;
    height: 110px;
    flex-shrink: 0;
}
.claim-text .label {
    font-size: 10pt;
    color: #555;
    margin-bottom: 5px;
}
.claim-text .url {
    font-family: 'JetBrains Mono', 'Courier New', monospace;
    font-size: 11pt;
    font-weight: 700;
    color: #2C2C2C;
    word-break: break-all;
}

/* ── Sign-off ── */
.sign { margin-top: 16px; }
.sign p { margin-bottom: 5px; }
.sign .sig-name {
    font-family: 'Outfit', 'Arial Black', sans-serif;
    font-weight: 800;
    font-size: 13pt;
}
.sign .sig-company { font-size: 10pt; color: #2C2C2C; margin-top: 2px; }

/* ── PS: plain italic, no border ── */
.ps {
    margin-top: 10px;
    font-style: italic;
    font-size: 10pt;
    color: #2C2C2C;
}

/* ── Footer ── */
.foot {
    margin-top: 18px;
    padding-top: 8px;
    border-top: 1px solid #2C2C2C;
    font-family: 'JetBrains Mono', 'Courier New', monospace;
    font-size: 8pt;
    color: #555;
    line-height: 1.5;
}
"""

# QR image via qrserver — PostGrid substitutes {{claimUrl}} at render time.
_QR_SRC = "https://api.qrserver.com/v1/create-qr-code/?size=120x120&amp;data={{{{claimUrl}}}}"


# ── UK template (A4) ────────────────────────────────────────────────────────

def uk_html(logo_uri: str | None = None) -> str:
    logo = logo_uri or _logo_data_uri()
    logo_img = f'<img src="{logo}" alt="Antek Automation">' if logo else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>{_SHARED_CSS}</style>
</head>
<body>

  <!-- HEADER: logo only — sender address is in footer; PostGrid stamps return on envelope -->
  <div class="header">
    <div class="brandmark">
      {logo_img}
      <span class="name">Antek&nbsp;Automation</span>
    </div>
  </div>

  <!-- RECIPIENT ADDRESS — single pre-formatted block var (avoids {{to.*}} uppercase) -->
  <div class="addressee">{{{{addrBlock}}}}</div>

  <!-- BODY -->
  <div class="body">

    <p>Dear {{{{salutation}}}},</p>

    <div class="finding">{{{{headline}}}}</div>

    <p>I run Antek Automation in Andover. I have been checking how {{{{town}}}}
       {{{{sector}}}} appear when people ask AI tools like ChatGPT for a
       recommendation &mdash; which is how more and more customers now begin
       their search.</p>

    <p>Roughly 85% of UK businesses have zero measurable AI visibility. Most
       have no idea, because their AI presence does not show up in the places
       they usually check.</p>

    <p>I put together a short AI Visibility Check report for {{{{to.companyName}}}}. It
       shows exactly where you appear across ChatGPT, Perplexity and Google&rsquo;s AI
       results, and where a competitor appears instead. It is free and it is
       already prepared. You just need to claim it.</p>

    <div class="claim">
      <img class="qr" src="{_QR_SRC}" alt="Scan to claim your report">
      <div class="claim-text">
        <div class="label">Scan the code, or go to:</div>
        <div class="url">{{{{claimUrl}}}}</div>
      </div>
    </div>

    <div class="sign">
      <p>Best regards,</p>
      <div class="sig-name">Andy Norman</div>
      <div class="sig-company">Antek Automation</div>
    </div>

    <p class="ps">PS. No catch. The report exists either way. I&rsquo;d rather you saw it.</p>

  </div>

  <!-- FOOTER -->
  <div class="foot">
    Antek Automation &middot; 4 Highlands Road, Andover, Hampshire, SP10 2PX &middot; 0333 038 9960 &middot; antekautomation.com
  </div>

</body>
</html>"""


# ── US template (US Letter) ──────────────────────────────────────────────────

def us_html(logo_uri: str | None = None) -> str:
    logo = logo_uri or _logo_data_uri()
    logo_img = f'<img src="{logo}" alt="Antek Automation">' if logo else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>{_SHARED_CSS}</style>
</head>
<body>

  <!-- HEADER: logo only -->
  <div class="header">
    <div class="brandmark">
      {logo_img}
      <span class="name">Antek&nbsp;Automation</span>
    </div>
  </div>

  <!-- RECIPIENT ADDRESS — single pre-formatted block var (avoids {{to.*}} uppercase) -->
  <div class="addressee">{{{{addrBlock}}}}</div>

  <!-- BODY -->
  <div class="body">

    <p>Dear {{{{salutation}}}},</p>

    <div class="finding">{{{{headline}}}}</div>

    <p>I run Antek Automation, an AI automation company &mdash; I work inside tools
       like ChatGPT, Gemini and Perplexity every day. I have been checking how
       {{{{town}}}} {{{{sector}}}} appear when buyers ask AI for a recommendation,
       because that is how more and more people now start their search.</p>

    <p>Roughly 85% of small businesses have zero measurable AI visibility. Most
       have no idea, because their AI presence does not show up in the places
       they usually check.</p>

    <p>I put together a short AI Visibility Check report for {{{{to.companyName}}}}. It
       shows exactly where you appear across ChatGPT, Perplexity and Google&rsquo;s AI
       results, and where a competitor appears instead. It is free and it is
       already prepared. You just need to claim it.</p>

    <div class="claim">
      <img class="qr" src="{_QR_SRC}" alt="Scan to claim your report">
      <div class="claim-text">
        <div class="label">Scan the code, or go to:</div>
        <div class="url">{{{{claimUrl}}}}</div>
      </div>
    </div>

    <div class="sign">
      <p>Best regards,</p>
      <div class="sig-name">Andy Norman</div>
      <div class="sig-company">Antek Automation</div>
    </div>

    <p class="ps">PS. No catch. The report exists either way. I&rsquo;d rather you saw it.</p>

  </div>

  <!-- FOOTER -->
  <div class="foot">
    Antek Automation &middot; antekautomation.com
  </div>

</body>
</html>"""
